//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckingProgramCode.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CheckingProgramCode.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на abstract
        ///as
        ///base
        ///bool	
        ///break
        ///byte
        ///case
        ///catch
        ///char
        ///checked
        ///class
        ///const
        ///continue
        ///decimal
        ///default
        ///delegate	
        ///do
        ///double
        ///else
        ///enum
        ///event
        ///explicit
        ///extern
        ///false
        ///finally
        ///fixed
        ///float
        ///for
        ///foreach
        ///goto
        ///if
        ///implicit	
        ///in
        ///int
        ///interface
        ///internal	
        ///is
        ///lock
        ///long
        ///namespace	
        ///new
        ///null
        ///object
        ///operator	
        ///out
        ///override
        ///params
        ///private	
        ///protected
        ///public
        ///readonly
        ///ref	
        ///return
        ///sbyte
        ///sealed
        ///short	
        ///sizeof
        ///stackalloc
        ///static
        ///string	
        ///struct
        ///switch
        ///this
        ///throw	
        ///true
        ///try
        ///typeof
        ///uin [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string KeyWordsCSharp {
            get {
                return ResourceManager.GetString("KeyWordsCSharp", resourceCulture);
            }
        }
    }
}
